name: Publish Helm Charts

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # To commit Chart.yaml updates
  packages: write # To publish the Helm charts

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: [tfc-agent, tfc-agent-tailscale]
    env:
      CHART_NAME: ${{ matrix.chart }}
      REGISTRY: ghcr.io/${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Check if Chart.yaml needs version bump
        id: check_version
        working-directory: charts/${{ env.CHART_NAME }}
        run: |
          current_version=$(grep '^version:' Chart.yaml | awk '{print $2}')
          if [ "$current_version" = "${{ steps.get_version.outputs.version }}" ]; then
            echo "bump_needed=false" >> $GITHUB_OUTPUT
          else
            echo "bump_needed=true" >> $GITHUB_OUTPUT
          fi

      - name: Update Chart.yaml version if needed
        if: steps.check_version.outputs.bump_needed == 'true'
        working-directory: charts/${{ env.CHART_NAME }}
        run: |
          sed -i.bak "s/^version: .*/version: ${{ steps.get_version.outputs.version }}/" Chart.yaml

      - name: Commit updated Chart.yaml back to main if changed
        if: steps.check_version.outputs.bump_needed == 'true'
        working-directory: charts/${{ env.CHART_NAME }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout main
          git pull origin main
          git add Chart.yaml
          git diff --cached --quiet || (
            git commit -m "chore(${CHART_NAME}): bump chart version to ${{ steps.get_version.outputs.version }}"
            git push origin main
          )

      - name: Run lint
        run: make lint

      - name: Package chart
        run: make package

      - name: Publish chart to GHCR
        run: make publish
